export const REQUEST_RESTAURANTS = 'REQUEST_RESTAURANTS';
export const RECEIVE_RESTAURANTS = 'RECEIVE_RESTAURANTS';
export const REQUEST_RESTAURANT = 'REQUEST_RESTAURANT';
export const RECEIVE_RESTAURANT = 'RECEIVE_RESTAURANT';

// Restaurant list
export const REQUEST_RESTAURANT_LIST = 'REQUEST_RESTAURANT_LIST';  
export const RECEIVE_RESTAURANT_LIST = 'RECEIVE_RESTAURANT_LIST';  

// Ordering
// export const ORDER_RECENT   = 'ORDER_RECENT'; 
// export const ORDER_REVIEW   = 'ORDER_REVIEW'; 
// export const ORDER_AVERAGE  = 'ORDER_AVERAGE'; 
// export const ORDER_LIKE     = 'ORDER_LIKE';

// pagination
// export const REQUEST_PAGE_NUMBER    = 'REQUEST_PAGE_NUMBER';
// export const REQUEST_PAGE_PREV      = 'REQUEST_PAGE_PREV';
// export const REQUEST_PAGE_NEXT      = 'REQUEST_PAGE_NEXT';
// export const REQUEST_PAGE_PREV_SET  = 'REQUEST_PAGE_PREV_SET';
// export const REQUEST_PAGE_NEXT_SET  = 'REQUEST_PAGE_NEXT_SET';
// export const RECEIVE_PAGE           = 'RECEIVE_PAGE';